version: '3'

services:
  postgress:
    restart: always
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  blog:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgress